version: '3.8'

services:
  backend:
    build: ./server
    restart: on-failure
    volumes:
      - ./home/gonbvza/examai/volume:/usr/src/server/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      db:
          condition: service_healthy       
  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post1258
      - POSTGRES_DB=examai
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web: 
    build: ./client
    ports: 
      - 8080:80
    depends_on:
      - backend


volumes:
  postgres_data:


