[build]
  base = "/"
  publish = "client"
  command = "npm install --save-exact react react-dom @types/react@18.2.0 @types/react-dom@18.2.0 react-router-dom @fortawesome/react-fontawesome @fortawesome/free-solid-svg-icons @fortawesome/fontawesome-svg-core react-modal @types/react-modal js-cookie @types/js-cookie && npm run build"  # Adjust this for your project