# Generated by Django 5.1.6 on 2025-02-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userManagement", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
    ]
